name: 'Green blue deploy'
description: 'Green blue kubernetes deploy'
inputs:
  kube-config:
    description: 'Kubernetes config'
    required: true
    default: ''
  deployment-name:
    description: 'Deployment name'
    required: true
    default: ''
  service-name:
    description: 'Service name'
    required: true
    default: ''
  version:
    description: 'Deployment version'
    required: true
    default: 'latest'
  namespace:
    description: 'Namespace'
    required: true
    default: ''
  accepted-restarts:
    description: 'Accepted restarts'
    required: true
    default: '1'
  restart-wait:
    description: 'Wait after rollout for restarts'
    required: true
    default: '10'
outputs:
  test:
    description: 'test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kube-config }}
    - ${{ inputs.deployment-name }}
    - ${{ inputs.service-name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.accepted-restarts }}
    - ${{ inputs.restart-wait }}
    - ${{ inputs.version }}
